version: '2'
services:
  checkout_app:
    extends:
      file: docker-compose.apps.yml
      service: checkout_app
    command: mvn spring-boot:run -Drun.profiles=dev
    volumes:
      - ./checkout-app:/app
    depends_on:
      - checkout_db
      - rabbitmq_master
  gateway_app:
    extends:
      file: docker-compose.apps.yml
      service: gateway_app
    command: mvn spring-boot:run -Drun.profiles=dev
    volumes:
      - ./gateway-app:/app
    depends_on:
      - gateway_db
      - rabbitmq_master
  reports_app:
    extends:
      file: docker-compose.apps.yml
      service: reports_app
    command: mvn spring-boot:run -Drun.profiles=dev
    volumes:
      - ./reports-app:/app
    depends_on:
      - reports_db
      - rabbitmq_master
  notifications_app:
    extends:
      file: docker-compose.apps.yml
      service: notifications_app
    command: mvn spring-boot:run -Drun.profiles=dev
    volumes:
      - ./notifications-app:/app
    depends_on:
      - notifications_db
      - rabbitmq_master
      - mail_server