version: '2'
services:
  checkout_app:
    extends:
      file: docker-compose.apps.yml
      service: checkout_app
    depends_on:
      - checkout_db
      - rabbitmq_master
  gateway_app:
    extends:
      file: docker-compose.apps.yml
      service: gateway_app
    depends_on:
      - gateway_db
      - rabbitmq_master
  reports_app:
    extends:
      file: docker-compose.apps.yml
      service: reports_app
    depends_on:
      - reports_db
      - rabbitmq_master
  notifications_app:
    extends:
      file: docker-compose.apps.yml
      service: notifications_app
    depends_on:
      - notifications_db
      - rabbitmq_master
      - mail_server