version: '2'
services:
  checkout_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54321:5432"
  delivery_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54322:5432"
  reports_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54323:5432"
  notifications_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54324:5432"
  rabbitmq_master:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE="clusteramqp-01-2017"
    ports:
      - "8080:15672"
  rabbitmq_slave:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE="clusteramqp-01-2017"
    ports:
      - "9080:15672"
  mail_server:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
