version: '2'
services:
  checkout_app:
    build: ./checkout-app
    command: sh -c "mvn -Dtest=**.acceptance.**.*Test clean package -Drun.profiles=ci"
    ports:
      - "9010:8080"
    env_file:
        - resources/docker/.env.dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://checkout_db:5432/amqpadmin
  gateway_app:
    build: ./gateway-app
    command: sh -c "mvn -Dtest=**.acceptance.**.*Test clean package -Drun.profiles=ci"
    ports:
      - "9020:8080"
    env_file:
      - resources/docker/.env.dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gateway_db:5432/amqpadmin
  reports_app:
    build: ./reports-app
    command: sh -c "mvn -Dtest=**.acceptance.**.*Test clean package -Drun.profiles=ci"
    ports:
      - "9030:8080"
    env_file:
        - resources/docker/.env.dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://reports_db:5432/amqpadmin
  notifications_app:
    build: ./notifications-app
    command: sh -c "mvn -Dtest=**.acceptance.**.*Test clean package -Drun.profiles=ci"
    ports:
      - "9040:8080"
    env_file:
        - resources/docker/.env.dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notifications_db:5432/amqpadmin