version: '2'
services:
  checkout_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54321:5432"
  delivery_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54322:5432"
  reports_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54323:5432"
  notifications_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54324:5432"
  rabbitmq_server:
    image: rabbitmq:3-management
    ports:
      - "9079:15671"
      - "9080:15672"
      - "9081:25672"
      - "9082:4369"
      - "9083:5671"
      - "9084:5672"
      - "9085:5432"
  mail_server:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
