###########   
# STORAGE #
###########
spring:
  datasource: 
    url: "jdbc:postgresql://gateway_db:5432/amqpadmin"
    driver-class-name: org.postgresql.Driver
    username: amqpadmin
    password: amqpadmin
  hibernate:
    show_sql: true
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false

# STORAGE MIGRATIONS
liquibase:
  enabled: true
