FROM java:openjdk-8-alpine

RUN MAVEN_VERSION=3.3.9 \
 && cd /usr/share \
 && wget -q http://mirror.nbtelecom.com.br/apache/maven/maven-3/3.3.9/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz -O - | tar xzf - \
 && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
 && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven

COPY . /app
WORKDIR /app
RUN mvn clean install

CMD ["mvn"]
