spring:
  profiles:
    active: test
  application:
    name: '@artifactId@'
    version: '@project.version@'
    
#################    
# DB MIGRATIONS #
#################       
liquibase:
  change-log: "classpath:db/master-changelog.xml"