###########   
# STORAGE #
###########
spring:
  datasource: 
    url: "jdbc:postgresql://checkout_db:5432/amqpadmin"
    driver-class-name: org.postgresql.Driver
    username: amqpadmin
    password: amqpadmin
  hibernate:
    show_sql: true
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
########    
# MAIL #
########
mail:
  host: mail_server
  port: 1025

#########    
# QUEUE #
#########
rabbitmq:
  host: rabbitmq_master
  port: 5672
  username: guest
  password: guest
  listener:
    concurrency: 3
    max-concurrency: 5
    retry:
      enabled: true
      initial-interval: 2000
      max-attempts: 2
      multiplier: 1.5
      max-interval: 5000
